### ISSUE TITLE
reporte practica 8 consulta de datos 

### ISSUE THREAD

**Issue by IsaacCS1** [SistemasTecTlaxiaco/Practica-de-consulta-de-datos-en-Visual#1]
[PracticaNum8.pdf](https://github.com/SistemasTecTlaxiaco/Practica-de-consulta-de-datos-en-Visual/files/8854872/PracticaNum8.pdf)

**Comment by abicoronel** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
